# cloudbuild.yaml
steps:
  # Build and deploy the backend service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Build Backend
    dir: "backend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build -t gcr.io/$PROJECT_ID/backend:latest .
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Push Backend
    args:
      - "docker"
      - "push"
      - "gcr.io/$PROJECT_ID/backend:latest"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Deploy Backend
    args:
      - "gcloud"
      - "run"
      - "deploy"
      - "siatplanner-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/backend:latest"
      - "--platform"
      - "managed"
      - "--region"
      - "<YOUR_REGION>"
      - "--allow-unauthenticated"

  # Build and deploy the client service
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Build Client
    dir: "client"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build -t gcr.io/$PROJECT_ID/client:latest .
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Push Client
    args:
      - "docker"
      - "push"
      - "gcr.io/$PROJECT_ID/client:latest"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Deploy Client
    args:
      - "gcloud"
      - "run"
      - "deploy"
      - "siatplanner-client"
      - "--image"
      - "gcr.io/$PROJECT_ID/client:latest"
      - "--platform"
      - "managed"
      - "--region"
      - "Northamerica-Northeast1"
      - "--allow-unauthenticated"

images:
  - gcr.io/$PROJECT_ID/backend:latest
  - gcr.io/$PROJECT_ID/client:latest
