version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/test"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/clientapp:delegated
      - /clientapp/node_modules
      - /clientapp/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  backend_node_modules:
  client_node_modules:
  client_next: 